name: Docker build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cp .env.example .env && make build

      - name: Run isort
        run: make isort

      - name: Run flake8
        run: make flake8

      - name: Run mypy
        run: make mypy

      - name: Run Tests
        run: make tests
